spring.application.name=mediaforge

# MySQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mediaforge}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# File Upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Media Storage
media.storage.original=${MEDIA_STORAGE_ORIGINAL:storage/original}
media.storage.optimized=${MEDIA_STORAGE_OPTIMIZED:storage/optimized}

frontend.url=${FRONTEND_URL:http://localhost:5173}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000