spring.application.name=mediaforge

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/mediaforge
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# File Upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Media Storage
media.storage.original=storage/original
media.storage.optimized=storage/optimized

jwt.secret=MediaForgeSecretKeyForJwtAuthentication2026VerySecure
jwt.expiration=86400000